name: build

on:
  push:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: build x86_64-pc-windows-msvc
      run: cargo build --release --verbose --target x86_64-pc-windows-msvc
    - run: cp target/x86_64-pc-windows-msvc/release/lailai.exe lailai-${{ steps.get_version.outputs.VERSION }}-win-x86_64.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        prerelease: true
        files: lailai-${{ steps.get_version.outputs.VERSION }}-win-x86_64.exe
        generate_release_notes: false
        name: master
  build-linux-x86:
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        override: true
    - run: sudo apt-get install musl-tools
    - name: build ${{ matrix.target }}
      run: cargo build --release --verbose --target ${{ matrix.target }}
    - run: strip target/${{ matrix.target }}/release/lailai
    - run: cp target/${{ matrix.target }}/release/lailai lailai-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        prerelease: true
        files: lailai-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}
        generate_release_notes: false
        name: master
  build-linux-aarch64:
    strategy:
      matrix:
        target: 
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    runs-on: ubuntu-latest

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target ${{ matrix.target }}

    # - run: sudo apt-get install musl-tools
    # - name: build ${{ matrix.target }}
    #   run: cargo build --release --verbose --target ${{ matrix.target }}
    # - run: strip target/${{ matrix.target }}/release/lailai
    # - run: cp target/${{ matrix.target }}/release/lailai lailai-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        prerelease: true
        files: lailai-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}
        generate_release_notes: false
        name: master
  build-mac:
    strategy:
      matrix:
        target: 
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    runs-on: macos-latest

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        override: true
    - name: build ${{ matrix.target }}
      run: cargo build --release --verbose --target ${{ matrix.target }}
    - run: strip target/${{ matrix.target }}/release/lailai
    - run: cp target/${{ matrix.target }}/release/lailai lailai-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        prerelease: true
        files: lailai-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}
        generate_release_notes: false
        name: master